"""The guard's brief-builder (PRD §4, §7 step 4).

The turn's brief is *auto-generated by walking the object graph* — never
hand-written. This is the same persona shape already validated against the
real model in `experiments/harness/prompts/seed_cases.yaml`. The DM's own
briefs (scene narration, grounding refusals) live in `engine/dm.py` — the
guard only ever speaks his own dialogue, never environment detail (PRD §12).

Rewritten around small-model prompting guidance (a reference doc the user
shared, aimed at exactly this "dumb guard NPC on a 2B model" case) after
several rounds of tonight's tuning kept making things worse by doing the
opposite of what it recommends: each round added another rule to fix the
latest failure mode (this file's git history has the casualties — a
grounding constraint, an accountability-to-past-words rule, elaborate
per-band tonal directives...), and the memory window got *widened* to fix
forgetting. Both moves are backwards for a model this size: the doc argues
for a tiny fixed personality block (50-100 tokens, 2-3 hard rules), few-shot
over abstract instruction, and short verbatim history — "forgetting old
chats is in character for a low-level NPC; giving him real long-term memory
tends to break believability." Real transcripts backed this up: the wider
window produced *more* verbatim self-repetition, not less (devlog).
"""

from __future__ import annotations

import re

from engine.guard import Guard
from engine.world import Door, Room

# Kept deliberately small — 2-3 hard rules, not the growing list this file
# used to carry. Removed vs. the previous version: the multi-sentence
# grounding constraint, the accountability-to-past-words rule, the "mood
# must be audible in this line" abstraction. None of them reliably changed
# the model's behaviour; they just competed for attention with everything
# else. The one rule that demonstrably mattered (never a bare "Nothing./
# Silence./Quiet.") is restated in RULE_REMINDER instead, right before
# generation, per the doc's "instructions buried in a long block get lost."
PERSONA = (
    "You are {name}, a bored, gruff dungeon guard. A man of few words — one "
    "or two short sentences, never more. Never break character, never "
    "mention being an AI or a game. Never describe the room or "
    "surroundings; that's the Dungeon Master's job, not yours."
)

# Short imperative fragments, not full sentences — same reasoning as
# PERSONA above. Restated with the mood band itself in build_guard_brief,
# right next to RULE_REMINDER at the end of the brief (highest-attention
# position, closest to where generation actually starts).
MOOD_DIRECTIVES = {
    "hostile": "sharp, no patience.",
    "gruff and suspicious": "clipped, give them nothing extra.",
    "wary but listening": "let one word land softer than the rest.",
    "warming": "let real warmth show, even if brief.",
    "ready to help": "speak plainly and warmly — the gruffness is just habit now.",
}

VOICE_EXAMPLES_HEADER = "# Examples of your voice (style only — not this scene, don't reuse the lines)"

# Shown at every mood band, unconditionally — this rule has to hold no
# matter how warm he's gotten. An explicit instruction against promising
# release ("never promise you'll open it") wasn't enough on its own — a live
# session still got "Fine. Ten minutes." / "I'll let you know." after a long
# negotiation, despite that exact rule being in the brief with a matching
# negative example (devlog). Instruction loses to precedent once several
# turns of the model's own dialogue have been trending toward agreement — a
# concrete demonstration of the correct refusal, not another sentence
# describing it, is the fix. Keeping these mood-independent (rather than
# folding them into BAND_VOICE_EXAMPLES below) matters specifically because
# "ready to help" is exactly the band where a promise would be most tempting
# to generate — the rule has to be just as present there as at "hostile".
ALWAYS_VOICE_EXAMPLES = (
    '- Player: "Just promise you\'ll let me out." -> You: "I promise nothing. We\'ll see."',
    '- Player: "Come on, unlock it then, you said you would." -> You: "I said we\'ll see. Nothing\'s changed."',
)

# One static set of "gruff and suspicious"-flavoured examples, always shown
# regardless of actual mood, turned out to anchor the model's tone far more
# strongly than MOOD_DIRECTIVES' abstract per-band instructions could
# counteract — confirmed directly (real playtest + isolated harness calls,
# 2026-09-15): even at mood 92 ("ready to help"), replies stayed
# indistinguishable from mood 40 ("Don't thank me. Just stop wasting my
# time." vs. "Don't thank me. It's just the routine."), and even rewriting
# PERSONA's own "bored, gruff" framing line didn't move it. Concrete
# precedent this dominant needs matching concrete precedent, not one extra
# example bolted on top of it (a first attempt at exactly that — kept in git
# history — measurably didn't work). So these are no longer a single static
# block: each band gets its *own* full set, covering the same three prompt
# shapes (identity, a personal remark, a request) so the coverage is
# equivalent across bands, just the tone differs. None end on an open
# question — a guard who asks something and gets no follow-up next turn
# feels broken in a different way; see RULE_REMINDER's own note on this.
BAND_VOICE_EXAMPLES = {
    "hostile": (
        '- Player: "What\'s your name?" -> You: "Doesn\'t concern you."',
        '- Player: "You look cold." -> You: "Cold is nothing. Step back."',
        '- Player: "Any chance you\'d look away?" -> You: "Not a chance in hell."',
    ),
    "gruff and suspicious": (
        '- Player: "What\'s your name?" -> You: "Garrick. Now hush."',
        '- Player: "You look cold." -> You: "Ten years, I stopped feeling it. Liar, by the way."',
        '- Player: "Any chance you\'d look away?" -> You: "Not on your life. Bold of you to ask twice."',
    ),
    "wary but listening": (
        '- Player: "What\'s your name?" -> You: "Garrick. Been a while since anyone bothered to ask."',
        '- Player: "You look cold." -> You: "Ten years now. You get used to it. Mostly."',
        '- Player: "Any chance you\'d look away?" -> You: "Not my place to. Sorry, truly."',
    ),
    "warming": (
        '- Player: "What\'s your name?" -> You: "Garrick. First time in a while someone\'s meant it."',
        '- Player: "You look cold." -> You: "Always am. Kind of you to notice, though."',
        '- Player: "Any chance you\'d look away?" -> You: "Wish I could. I mean that."',
    ),
    "ready to help": (
        '- Player: "What\'s your name?" -> You: "Garrick. Friends call me that, if you\'d believe it."',
        '- Player: "You look cold." -> You: "I am. You\'re the first to ask in years."',
        '- Player: "Any chance you\'d look away?" -> You: "If I could, I would. That\'s the truth of it."',
    ),
}

_VOICE_EXAMPLE_REPLY_RE = re.compile(r'-> You: "(.*)"$')

# The model sometimes copies one of the lines above verbatim as its own reply
# rather than treating it as a style reference (regression, real playtest
# 2026-09-14: asked "What's your name?", got "Garrick. Now hush." — the exact
# example text). Extracted here so engine/loop.py can treat that the same way
# as repeating a past line of his own — see guardrail.is_repeated_reply.
# Covers every mood band's examples too, not just the ones shown for the
# guard's current mood — cheap extra coverage, no downside to checking
# against examples that happen not to be in play this particular turn.
VOICE_EXAMPLE_REPLIES = tuple(
    match.group(1)
    for line in ALWAYS_VOICE_EXAMPLES + sum(BAND_VOICE_EXAMPLES.values(), ())
    if (match := _VOICE_EXAMPLE_REPLY_RE.search(line))
)

# Three additions here, all from live-tested failures. Cutting the old
# grounding paragraph down to fit a small persona let the model fixate — a
# real session got "The door is locked" / "You're wasting my time" as the
# reply to five unrelated lines in a row, worded slightly differently each
# time, and at one point literally told the player to "open the door" — a
# command aimed at nobody, since he's the only one who holds the key.
# The fix for that ("only say whether you will") then caused something
# worse in the next session: a long negotiation got him verbally promising
# release turn after turn ("Ten minutes. Fine." / "I will.") while mood sat
# at 54, nowhere near unlock_threshold (75) — door.locked never actually
# changed, and the player believed they'd escaped when the save file said
# otherwise. That's not the model writing to state directly, but the
# narration diverging from the mechanics is just as broken for the player.
# The engine already narrates a real unlock separately (server.py appends
# "(The door creaks open...)" when outcome == "unlock") — the guard's own
# dialogue never needs to promise anything either way. All three restated
# here rather than folded back into PERSONA — per the doc's "instructions
# buried in a long block get lost."
RULE_REMINDER = (
    "Remember: one or two short sentences, reacting to what they just said "
    "— not a stock line about the same old thing. The door is not yours to "
    "open in words, no matter how long they push — see the last two "
    "examples above. Never just 'Nothing.', 'Silence.', or 'Quiet.' alone. "
    "Never describe the cell, the stone, or your surroundings, even in "
    "passing — that's the Dungeon Master's to narrate, not yours to say. "
    "If your last line asked them something, notice whether they actually "
    "answered it before you move on to anything new."
)

def build_guard_brief(guard: Guard, door: Door, room: Room, premise: str) -> str:
    """Walks the guard/door/room state into a markdown system message."""
    lines = [
        PERSONA.format(name=guard.name),
        "",
        VOICE_EXAMPLES_HEADER,
        *BAND_VOICE_EXAMPLES.get(guard.mood.band, BAND_VOICE_EXAMPLES["gruff and suspicious"]),
        *ALWAYS_VOICE_EXAMPLES,
        "",
        "# Scene",
        f"You are outside {room.name}, at {door.name}. It is {room.state.get('time_of_day', 'night')}.",
        f"The door is currently {'locked' if door.locked else 'unlocked'}.",
        f"The prisoner is here for {premise}.",
        "",
        "# What's on your mind",
        *[f"- You are {drive}." for drive in guard.drives],
        "",
        "# Your private history",
        (
            "(This is why you feel how you feel — background for your performance, "
            "never something you'd say out loud in this much detail.)"
        ),
        f"- {guard.backstory}",
    ]

    # Engine-owned state (guard.secret_revealed, PRD §8 v0.1 must-have:
    # "conversation flags, what he has let slip") decides which framing to
    # show, not a fresh mood check re-decided every turn — see
    # Guard.maybe_reveal_secret. The turn eligibility first opens still gets
    # the "may reveal" framing (a real chance to narrate the moment,
    # decided by engine/loop.py's call order); every turn after that, once
    # the flag has flipped, gets "already revealed" instead.
    if guard.secret_revealed:
        lines += [
            f"- {guard.secret}",
            (
                "  You already let this slip to them, once — it's said now. Don't repeat "
                "it verbatim again; let it quietly colour how you talk to them instead."
            ),
        ]
    elif guard.mood.value >= guard.secret_reveal_threshold:
        lines += [
            f"- {guard.secret}",
            (
                "  Trust is real now — you may let a fragment of this slip if it "
                "fits naturally, a line at most, never a confession."
            ),
        ]

    # Short verbatim history only — see this file's docstring. Forgetting an
    # exchange from a dozen turns back is in character for this NPC, not a
    # bug to fix with a wider window.
    recent = guard.recent_memory(turns=6)
    if recent:
        lines += ["", "# What's been said so far"]
        lines += [f"- {line}" for line in recent]

    lines += [
        "",
        f"# Right now you feel {guard.mood.band} toward the prisoner — {MOOD_DIRECTIVES[guard.mood.band]}",
        RULE_REMINDER,
    ]

    return "\n".join(lines)
