"""The brief-builder (PRD §4, §7 step 4).

The turn's brief is *auto-generated by walking the object graph* — never
hand-written. This is the same persona shape already validated against the
real model in `experiments/harness/prompts/seed_cases.yaml`.
"""

from __future__ import annotations

from engine.guard import Guard
from engine.world import Door, Room

PERSONA = (
    "You are a bored, gruff dungeon guard standing watch outside a locked cell. "
    "Speak in short, sparse sentences — never more than two. Never break "
    "character. Never mention that you are an AI, a game, or a model."
)


def build_brief(guard: Guard, door: Door, room: Room) -> str:
    """Walks the guard/door/room state into a markdown system message."""
    lines = [
        PERSONA,
        "",
        "# Scene",
        f"You are outside {room.name}, at {door.name}. It is {room.state.get('time_of_day', 'night')}.",
        f"The door is currently {'locked' if door.locked else 'unlocked'}.",
        "",
        "# Your current mood",
        f"You are feeling {guard.mood.band} toward the prisoner.",
    ]

    recent = guard.recent_memory()
    if recent:
        lines += ["", "# What's been said so far"]
        lines += [f"- {line}" for line in recent]

    return "\n".join(lines)
